name: Deploy Popular Seguros Fullstack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------
      # Setup .NET
      # -----------------------
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      # -----------------------
      # Setup Node
      # -----------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # -----------------------
      # Build Backend
      # -----------------------
      - name: Publish Poliza
        run: dotnet publish PopularSeguros.Microservicios/Poliza/Poliza.csproj -c Release -o publish-poliza

      - name: Publish Cliente
        run: dotnet publish PopularSeguros.Microservicios/Cliente/Cliente.csproj -c Release -o publish-cliente

      - name: Publish Autenticacion
        run: dotnet publish PopularSeguros.Microservicios/Autenticacion/Autenticacion.csproj -c Release -o publish-autenticacion

      # -----------------------
      # Build Frontend
      # -----------------------
      - name: Build Frontend
        working-directory: popular-seguros-polizas-web
        run: |
          npm install
          npm run build

      # -----------------------
      # Deploy to VPS
      # -----------------------
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # BACKEND
            cd /var/www/backends/popular-seguros-polizas
            git pull origin main

            dotnet publish PopularSeguros.Microservicios/Poliza/Poliza.csproj -c Release -o publish-poliza
            dotnet publish PopularSeguros.Microservicios/Cliente/Cliente.csproj -c Release -o publish-cliente
            dotnet publish PopularSeguros.Microservicios/Autenticacion/Autenticacion.csproj -c Release -o publish-autenticacion

            systemctl restart poliza
            systemctl restart cliente
            systemctl restart autenticacion

            # FRONTEND
            cd /var/www/frontends/popular-seguros-web

            npm install
            npm run build